version: "3.9"
services:
  ubuntu:
    image: ubuntu:focal
    volumes:
      - .:/code
    command: ["sleep","infinity"]

    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
  ubuntu18:
    image: ubuntu:bionic
    volumes:
      - .:/code
    command: ["sleep","infinity"]
